import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  atlasSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Taxonomy',
      items: [
        'taxonomy/overview',
        'taxonomy/security-goals',
        'taxonomy/confidentiality',
        'taxonomy/integrity',
        'taxonomy/authenticity',
        'taxonomy/anonymity',
        'taxonomy/unlinkability',
        'taxonomy/forward-secrecy',
        'taxonomy/verifiability',
        'taxonomy/auditability',
        'taxonomy/accountability',
        'taxonomy/deniability',
        'taxonomy/non-repudiation',
        'taxonomy/availability',
        'taxonomy/censorship-resistance',
        'taxonomy/additional-security-goals',
        'taxonomy/assumptions',
        'taxonomy/primitives-vs-protocols',
        'taxonomy/composability',
      ],
    },
    {
      type: 'category',
      label: 'Assumptions and Substrates',
      items: [
        'assumptions/discrete-logarithm',
        'assumptions/elliptic-curves',
        'assumptions/factoring-rsa',
        'assumptions/code-based-assumptions',
        'assumptions/pairings',
        'assumptions/lattices',
        'assumptions/random-oracle-model',
        'assumptions/trusted-setup',
        'assumptions/common-reference-strings',
        'assumptions/additional-substrates',
      ],
    },
    {
      type: 'category',
      label: 'Basic Primitives',
      items: [
        'primitives/overview',
        'primitives/primitive-engineering-concepts',
        'primitives/hash-functions',
        'primitives/symmetric-encryption',
        'primitives/authenticated-encryption',
        'primitives/message-authentication-codes',
        'primitives/key-derivation-functions',
        'primitives/password-hashing',
        'primitives/randomness-and-nonces',
        'primitives/commitments',
        'primitives/pedersen-commitments',
        'primitives/digital-signatures',
        'primitives/public-key-encryption',
        'primitives/key-encapsulation-and-exchange',
        'primitives/key-committing-encryption',
        'primitives/secret-sharing',
      ],
    },
    {
      type: 'category',
      label: 'Structured Primitives',
      items: [
        'structured-primitives/overview',
        'structured-primitives/advanced-structured-primitives',
        'structured-primitives/polynomial-commitments',
        'structured-primitives/vector-commitments',
        'structured-primitives/homomorphic-commitments',
        'structured-primitives/homomorphic-encryption',
        'structured-primitives/threshold-cryptography',
        'structured-primitives/functional-encryption',
        'structured-primitives/blind-signatures',
        'structured-primitives/verifiable-random-functions',
        'structured-primitives/verifiable-encryption',
        'structured-primitives/e-cash-primitives',
        'structured-primitives/timelock-and-vdfs',
        'structured-primitives/accumulators-and-merkle-trees',
      ],
    },
    {
      type: 'category',
      label: 'Proof Systems',
      items: [
        'proof-systems/overview',
        'proof-systems/proof-system-components',
        'proof-systems/zero-knowledge-proofs',
        'proof-systems/snarks-starks-bulletproofs',
        'proof-systems/range-proofs',
        'proof-systems/membership-proofs',
        'proof-systems/fri',
        'proof-systems/folding-schemes',
        'proof-systems/arithmetization',
        'proof-systems/sumcheck',
        'proof-systems/recursive-proofs',
        'proof-systems/lookup-arguments',
      ],
    },
    {
      type: 'category',
      label: 'Protocols',
      items: [
        'protocols/overview',
        'protocols/additional-protocol-families',
        'protocols/secure-channels',
        'protocols/password-authenticated-key-exchange',
        'protocols/oblivious-transfer',
        'protocols/private-information-retrieval',
        'protocols/anonymous-credentials',
        'protocols/anonymous-tokens',
        'protocols/blind-signature-credentials',
        'protocols/nullifiers',
        'protocols/oblivious-pseudorandom-functions',
        'protocols/private-set-intersection',
        'protocols/secure-aggregation',
        'protocols/mpc',
        'protocols/mixnets',
        'protocols/e-voting',
      ],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      items: [
        'design-patterns/overview',
        'design-patterns/operational-design-patterns',
        'design-patterns/domain-separation',
        'design-patterns/transcript-binding',
        'design-patterns/privacy-preserving-revocation',
        'design-patterns/anonymous-membership',
        'design-patterns/anti-double-use-nullifiers',
        'design-patterns/private-aggregation',
        'design-patterns/encrypt-then-prove',
        'design-patterns/threshold-issuance',
        'design-patterns/key-rotation-and-migration',
        'design-patterns/delayed-reveal',
        'design-patterns/reveal-only-a-function',
        'design-patterns/make-receipts-useless',
      ],
    },
    {
      type: 'category',
      label: 'Case Studies',
      items: [
        'case-studies/overview',
        'case-studies/additional-systems',
        'case-studies/private-payments',
        'case-studies/zk-rollups',
        'case-studies/secure-messaging',
        'case-studies/identity-wallets',
        'case-studies/encrypted-mempools',
        'case-studies/private-machine-learning-analytics',
        'case-studies/private-dao-voting',
        'case-studies/coercion-resistant-voting',
        'case-studies/anonymous-airdrop',
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      items: ['glossary/glossary'],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [
        'appendices/reading-list',
        'appendices/notation',
        'appendices/maturity-scale',
        'appendices/editorial-maturity-and-coverage',
        'appendices/comparison-matrices',
        'appendices/generated-comparison-matrices',
        'appendices/generated-relationship-graph',
        'appendices/concrete-algorithms-and-schemes',
        'appendices/diagram-authoring',
        'appendices/post-quantum-posture',
        'appendices/confidence-models',
        'appendices/metadata-leakage',
        'appendices/threat-model-checklist',
      ],
    },
  ],
};

export default sidebars;
